### ISSUE TITLE
 preprocessing	

### ISSUE THREAD

**Issue by chen-yuu** [Project-MONAI/research-contributions#24]
thank you for your work!!
I have a question about the result. I split the 3d data with 4x160x160x160 into 4x32x160x160 because of the limited memory.
but when it trained,the validation dice  reduced.I would appreciate it if you can give me some advice.
![R} FE6`G7)63`N0D N@}Q9](https://user-images.githubusercontent.com/34826417/143400591-63f5bd4d-4db7-4985-a5ca-6723e1d8afc7.png)

**Comment by ahatamiz** [comment]
Hi @chen-yuu 

I think this is very reasonable since your model is losing lots of spatial content by sub-sampling. I would recommend using `(4,128,128,128)` as your input size. In our experiments, we are able to use the same size with BRATS data using moderate amount of memory (~12G). If memory is still a bottleneck, I would recommend setting `conv_block=False`. 

Thanks
