### ISSUE TITLE
WARNING:root:NaN or Inf found in input tensor when training UNETR network.

### ISSUE THREAD

**Issue by mjq93** [Project-MONAI/research-contributions#27]
**Describe the bug**
Nan popped up while I was training the UNETR network.
WARNING:root:NaN or Inf found in input tensor.

**To Reproduce**
1. Go to 'UNETR/BTCV'
2. Run commands:
CUDA_VISIBLE_DEVICES=1,2,3 python main.py --distributed --feature_size=32  --batch_size=4 --logdir=unetr_test --optim_lr=1e-3 --lrschedule=warmup_cosine --infer_overlap=0.5  --save_checkpoint --data_dir=/data/BTCV/Abdomen/RawData/Training/ --workers=12

**Screenshots**
![image](https://user-images.githubusercontent.com/11666931/146330288-4a20b014-0646-498b-93df-b4fffcb0fb61.png)

**Environment (please complete the following information):**
 - OS
 - Python version  3.8
 - MONAI version [e.g. git commit hash] 
 - CUDA/cuDNN version CUDA11.1
 - GPU models and configuration. V100

**Comment by ahatamiz** [comment]
Hi @mjq93 

I am sorry you are facing this difficulty. We never ran into a NaN while training the UNETR. It is most likely caused by `DiceCELoss` as the values of denominator become very small. 

One quick fix it to set `squared_pred = False` in [DiceCELoss](https://github.com/Project-MONAI/research-contributions/blob/master/UNETR/BTCV/main.py#L155). This prevents the value of predictions, which are between 0 and 1, to further become smaller -- although we observed slightly better performance by squaring the predictions. 

Another fix would be to pass a larger value such as `smooth_dr = 1e-5` to prevent division by zero. I believe first fix will work out of the box and is more preferred. 

Thanks

**Comment by liuyanice** [comment]
I have met the same issue that  the loss become Nan when training,  both  the two fixs  are invalid. How do you solve them in the end?

**Comment by liuyanice** [comment]
@mjq93
I have met the same issue that the loss became Nan when training. Both the two fixs are invalid, how do you solve them in the end?

**Comment by liuyanice** [comment]
I have met the same issue that the loss became Nan when training. Both the two fixs are invalid, how do you solve them in the end?

**Comment by liuyanice** [comment]
![8}K 5)Y)YS WZ_A8 $}Z)AC](https://user-images.githubusercontent.com/21191835/190570183-147596f5-c8b8-4f61-ac1c-6533a3223292.png)

**Comment by liuyanice** [comment]
Thank you, I  have solved it
